spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true
  mvc:
    static-path-pattern: /static/**
  profiles:
      active: dev
  messages:
      basename: i18n/messages
  web:
    resources:
      static-locations: classpath:/static/

  mail:
    username: 506921079@qq.com
    password: qfcwwzlauddlbgid
    port: 587
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
